### ISSUE TITLE
OpenAI's services are not available in your country

### ISSUE THREAD

**Issue by ll903** [linweiyuan/go-chatgpt-api#1]
Why can't I use VPN in China

**Comment by linweiyuan** [comment]
> Why can't I use VPN in China

You must use supported nodes to login, even Hong Kong is forbidded.

If you node is actually a supported country, it doesn't mean that the real IP of this node is from this country.

Since only login needs to check this, you can simply copy the accessToken and cookies manually from online service and save them for further use.

**Comment by ll903** [comment]
这个项目也是你搞的呀，我买的是香港的服务器，香港节点不能用，是不是只能购买非中国的确的了？

**Comment by ll903** [comment]
从腾讯或者阿里购买非中国大陆的服务器是不是就行了呀

**Comment by linweiyuan** [comment]
> 从腾讯或者阿里购买非中国大陆的服务器是不是就行了呀

支持列表：https://platform.openai.com/docs/supported-countries

理论上没什么问题

**Comment by linweiyuan** [comment]
这个时候的 API 是响应及时的，你可以看我过往视频：[ChatGPT-Swing](https://linweiyuan.github.io/2023/02/25/ChatGPT-Swing.html#%E6%BC%94%E7%A4%BA%E8%A7%86%E9%A2%91)

因为当时有子域名可以用，就不用曲线救国，后来官方删了

**Comment by superen7527** [comment]
你博客我看过，不过你视频我这里都看不了，必须fq

你说的"这个时候"指的是这个issue创建的时候？

我个人其实挺喜欢用浏览器模拟过cf的方法，也尝试过。我记得去年年底刚套cf的时候还没有子域名用的也是cf的cookie头放进去就能用。相比于api我还是更喜欢web的api
